# ============================================================
# AWS Secrets Manager — all runtime secrets
# Secrets are created here with generated values.
# The EC2 instance reads them at startup via IAM role.
# ============================================================

# Random values generated by Terraform — stored in state (encrypt state!)
resource "random_password" "authentik_secret_key" {
  length  = 64
  special = false # Hex-safe
}

resource "random_password" "authentik_db_password" {
  length           = 48
  special          = true
  override_special = "!#$%^&*"
}

resource "random_password" "authentik_redis_password" {
  length           = 48
  special          = true
  override_special = "!#$%^&*"
}

resource "random_password" "guacamole_db_password" {
  length           = 48
  special          = true
  override_special = "!#$%^&*"
}

resource "random_password" "grafana_admin_password" {
  length           = 32
  special          = true
  override_special = "!#$%^&*"
}

resource "random_password" "grafana_secret_key" {
  length  = 64
  special = false
}

# ---- Authentik secrets ------------------------------------
resource "aws_secretsmanager_secret" "authentik" {
  name                    = "${local.name_prefix}/authentik"
  description             = "ZeroGate Authentik IdP secrets"
  recovery_window_in_days = 7

  tags = { Name = "${local.name_prefix}-secret-authentik" }
}

resource "aws_secretsmanager_secret_version" "authentik" {
  secret_id = aws_secretsmanager_secret.authentik.id

  secret_string = jsonencode({
    AUTHENTIK_SECRET_KEY      = random_password.authentik_secret_key.result
    AUTHENTIK_DB_PASSWORD     = random_password.authentik_db_password.result
    AUTHENTIK_REDIS_PASSWORD  = random_password.authentik_redis_password.result
  })
}

# ---- Guacamole secrets ------------------------------------
resource "aws_secretsmanager_secret" "guacamole" {
  name                    = "${local.name_prefix}/guacamole"
  description             = "ZeroGate Guacamole secrets"
  recovery_window_in_days = 7

  tags = { Name = "${local.name_prefix}-secret-guacamole" }
}

resource "aws_secretsmanager_secret_version" "guacamole" {
  secret_id = aws_secretsmanager_secret.guacamole.id

  secret_string = jsonencode({
    GUACAMOLE_DB_PASSWORD = random_password.guacamole_db_password.result
  })
}

# ---- Grafana secrets --------------------------------------
resource "aws_secretsmanager_secret" "grafana" {
  name                    = "${local.name_prefix}/grafana"
  description             = "ZeroGate Grafana secrets"
  recovery_window_in_days = 7

  tags = { Name = "${local.name_prefix}-secret-grafana" }
}

resource "aws_secretsmanager_secret_version" "grafana" {
  secret_id = aws_secretsmanager_secret.grafana.id

  secret_string = jsonencode({
    GRAFANA_ADMIN_PASSWORD = random_password.grafana_admin_password.result
    GRAFANA_SECRET_KEY     = random_password.grafana_secret_key.result
  })
}

# ---- Cloudflare secrets -----------------------------------
# Token is set manually after tunnel creation (can't auto-generate)
resource "aws_secretsmanager_secret" "cloudflare" {
  name                    = "${local.name_prefix}/cloudflare"
  description             = "ZeroGate Cloudflare Tunnel token"
  recovery_window_in_days = 7

  tags = { Name = "${local.name_prefix}-secret-cloudflare" }
}

resource "aws_secretsmanager_secret_version" "cloudflare" {
  secret_id = aws_secretsmanager_secret.cloudflare.id

  secret_string = jsonencode({
    CF_TUNNEL_TOKEN = "REPLACE_WITH_ACTUAL_TOKEN_AFTER_TUNNEL_CREATION"
  })

  lifecycle {
    # Don't overwrite if token was already set manually
    ignore_changes = [secret_string]
  }
}

# ---- Cloudflare API token (v1.1) ----------------------------------
# Stored in Secrets Manager so bootstrap.sh and threat-response.sh
# can read it without embedding in any file.
resource "aws_secretsmanager_secret" "cloudflare_api" {
  count                   = var.cf_api_token != "" ? 1 : 0
  name                    = "${local.name_prefix}/cloudflare-api"
  description             = "ZeroGate Cloudflare API token (WAF + Zero Trust management)"
  recovery_window_in_days = 7

  tags = { Name = "${local.name_prefix}-secret-cloudflare-api" }
}

resource "aws_secretsmanager_secret_version" "cloudflare_api" {
  count     = var.cf_api_token != "" ? 1 : 0
  secret_id = aws_secretsmanager_secret.cloudflare_api[0].id

  secret_string = jsonencode({
    CF_API_TOKEN  = var.cf_api_token
    CF_ZONE_ID    = var.cf_zone_id
    CF_ACCOUNT_ID = var.cf_account_id
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# Grant EC2 role permission to read the new secret
resource "aws_iam_role_policy" "cloudflare_api_read" {
  count = var.cf_api_token != "" ? 1 : 0
  name  = "${local.name_prefix}-cloudflare-api-read"
  role  = aws_iam_role.ec2.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = ["secretsmanager:GetSecretValue", "secretsmanager:DescribeSecret"]
      Resource = aws_secretsmanager_secret.cloudflare_api[0].arn
    }]
  })
}

# ---- Rotation metadata (rotation itself is handled by scripts/rotate-secrets.sh) ----
# AWS managed rotation via Lambda is optional. The rotation script handles it via:
#   ./scripts/rotate-secrets.sh --component all
# To enable AWS-managed rotation, create a rotation Lambda and uncomment:
#
# resource "aws_secretsmanager_secret_rotation" "authentik" {
#   secret_id           = aws_secretsmanager_secret.authentik.id
#   rotation_lambda_arn = "<ROTATION_LAMBDA_ARN>"
#   rotation_rules {
#     automatically_after_days = 90
#   }
# }
